const publications = [
  {
    year: "2025",
    venueTag: "ICASSP 2025",
    title: "Exploiting Robust Model Watermarking Against the Model Fine-Tuning Attack via Flat Minima Aware Optimizers",
    authors: ["Dongdong Lin", "Yue Li", "Bin Li", "Jiwu Huang"],
    venue: "IEEE International Conference on Acoustics, Speech and Signal Processing",
    note: "CCF-B | Oral",
    summary: "Studies robust model watermarking under fine-tuning attacks and improves resilience with flat-minima-aware optimization.",
    tags: ["Watermarking", "Fine-tuning", "Robustness"],
    featured: true,
    figureLabel: "Fine-Tuning Robustness",
    links: [
      { label: "Paper", url: "https://ieeexplore.ieee.org/document/10890107/" }
    ]
  },
  {
    year: "2025",
    venueTag: "arXiv 2025",
    title: "SOLIDO: A Robust Watermarking Method for Speech Synthesis via Low-Rank Adaptation",
    authors: ["Yue Li", "Weizhi Liu", "Dongdong Lin"],
    venue: "CoRR abs/2504.15035",
    note: "Preprint",
    summary: "Extends robust watermarking to speech synthesis and low-rank adaptation settings for audio generation models.",
    tags: ["Speech Synthesis", "LoRA", "Audio Watermarking"],
    featured: true,
    figureLabel: "Speech Watermarking Pipeline",
    links: [
      { label: "Paper", url: "https://dblp.org/rec/journals/corr/abs-2504-15035" }
    ]
  },
  {
    year: "2025",
    venueTag: "IEEE TDSC",
    title: "A CycleGAN Watermarking Method for Ownership Verification",
    authors: ["Dongdong Lin", "Benedetta Tondi", "Bin Li", "Mauro Barni"],
    venue: "IEEE Transactions on Dependable and Secure Computing",
    note: "Vol. 22(2): 1040-1054 | CCF-A",
    summary: "Presents a watermarking approach for ownership verification of CycleGAN models with security-oriented evaluation.",
    tags: ["CycleGAN", "Ownership Verification", "Model Watermarking"],
    featured: true,
    figureLabel: "CycleGAN Verification Framework",
    links: [
      { label: "Paper", url: "https://dblp.org/rec/journals/tdsc/LinTLB25" }
    ]
  },
  {
    year: "2024",
    venueTag: "arXiv 2024",
    title: "An Efficient Watermarking Method for Latent Diffusion Models via Low-Rank Adaptation",
    authors: ["Dongdong Lin", "Yue Li", "Benedetta Tondi", "Bin Li", "Mauro Barni"],
    venue: "CoRR abs/2410.20202",
    note: "Preprint",
    summary: "Investigates efficient watermark insertion for latent diffusion models using low-rank adaptation techniques.",
    tags: ["Diffusion Models", "LoRA", "AIGC Security"],
    featured: true,
    figureLabel: "Latent Diffusion Watermarking",
    links: [
      { label: "PDF", url: "https://arxiv.org/pdf/2410.20202" },
      { label: "Paper", url: "https://arxiv.org/abs/2410.20202" }
    ]
  },
  {
    year: "2024",
    venueTag: "ACM MM 2024",
    title: "GROOT: Generating Robust Watermark for Diffusion-Model-Based Audio Synthesis",
    authors: ["Weizhi Liu", "Yue Li", "Dongdong Lin", "Hui Tian", "Haizhou Li"],
    venue: "Proceedings of the 32nd ACM International Conference on Multimedia",
    note: "CCF-A",
    summary: "Develops a robust watermarking framework for audio generated by diffusion-based speech or sound synthesis systems.",
    tags: ["Audio Synthesis", "Diffusion", "Watermarking"],
    featured: true,
    figureLabel: "Audio Diffusion Watermarking",
    links: [
      { label: "PDF", url: "https://arxiv.org/pdf/2407.10471" },
      { label: "Paper", url: "https://arxiv.org/abs/2407.10471" },
      { label: "Project", url: "https://groot-gaw.github.io/" }
    ]
  },
  {
    year: "2023",
    venueTag: "PR 2023",
    title: "Watching the BiG Artifacts: Exposing DeepFake Videos via Bi-Granularity Artifacts",
    authors: ["Han Chen", "Yuezun Li", "Dongdong Lin", "Bin Li", "Junqiang Wu"],
    venue: "Pattern Recognition",
    note: "Vol. 135: 109179 | CCF-B",
    summary: "Exposes deepfake videos by exploring bi-granularity artifacts and improving forensic robustness.",
    tags: ["Deepfake Detection", "Forensics", "Multimedia Security"],
    featured: false,
    figureLabel: "Bi-Granularity Artifacts",
    links: [
      { label: "Paper", url: "https://faculty.hqu.edu.cn/ddlin/en/lwcg/240308/content/58035.htm" }
    ]
  },
  {
    year: "2022",
    venueTag: "IJCB 2022",
    title: "Exploiting Temporal Information to Prevent the Transferability of Adversarial Examples Against Deep Fake Detectors",
    authors: ["Dongdong Lin", "Benedetta Tondi", "Bin Li", "Mauro Barni"],
    venue: "IEEE International Joint Conference on Biometrics",
    note: "CCF-C | Oral",
    summary: "Uses temporal cues to reduce transferability of adversarial attacks against deepfake detectors.",
    tags: ["Adversarial Attack", "Deepfake", "Temporal Modeling"],
    featured: false,
    figureLabel: "Temporal Defense Strategy",
    links: [
      { label: "Paper", url: "https://faculty.hqu.edu.cn/ddlin/en/lwcg/240308/content/58036.htm" }
    ]
  }
];

const news = [
  {
    date: "2025",
    text: "ICASSP 2025 paper on robust model watermarking under fine-tuning attacks is now highlighted on the homepage."
  },
  {
    date: "2025",
    text: "Recent work extends model watermarking into speech synthesis with the SOLIDO framework."
  },
  {
    date: "2024",
    text: "Two representative 2024 directions now featured: latent diffusion watermarking and GROOT for audio synthesis."
  },
  {
    date: "2024",
    text: "TDSC work on CycleGAN ownership verification is listed as a selected publication."
  }
];

const selfName = "Dongdong Lin";
const publicationList = document.querySelector("#publication-list");
const newsList = document.querySelector("#news-list");
const chips = document.querySelectorAll(".chip");
const menuToggle = document.querySelector(".menu-toggle");
const siteNav = document.querySelector(".topbar-nav");

function renderAuthors(authors) {
  return authors.map((author) => {
    if (author === selfName) {
      return `<span class="author-self">${author}</span>`;
    }
    return author;
  }).join(", ");
}

function renderLinks(links) {
  return links.map((item) => `<a href="${item.url}">${item.label}</a>`).join("");
}

function renderPublications(filter = "all") {
  const filtered = publications.filter((paper) => {
    if (filter === "all") return true;
    if (filter === "selected") return paper.featured;
    return paper.year === filter;
  });

  publicationList.innerHTML = filtered.map((paper) => `
    <article class="publication-item">
      <div class="publication-figure" aria-hidden="true">
        <span class="figure-label">${paper.figureLabel}</span>
      </div>
      <div class="publication-body">
        <div class="publication-badges">
          <span class="publication-badge">${paper.venueTag}</span>
          <span class="publication-badge">${paper.year}</span>
        </div>
        <h3 class="publication-title">${paper.title}</h3>
        <p class="publication-authors">${renderAuthors(paper.authors)}</p>
        <p class="publication-meta">${paper.venue} | ${paper.note}</p>
        <p class="publication-summary">${paper.summary}</p>
        <div class="publication-tags">
          ${paper.tags.map((tag) => `<span class="publication-tag">${tag}</span>`).join("")}
        </div>
        <div class="publication-links">${renderLinks(paper.links)}</div>
      </div>
    </article>
  `).join("");
}

function renderNews() {
  newsList.innerHTML = news.map((item) => `
    <article class="news-item">
      <div class="news-date">${item.date}</div>
      <div class="news-text">${item.text}</div>
    </article>
  `).join("");
}

chips.forEach((chip) => {
  chip.addEventListener("click", () => {
    chips.forEach((item) => item.classList.remove("active"));
    chip.classList.add("active");
    renderPublications(chip.dataset.filter);
  });
});

menuToggle?.addEventListener("click", () => {
  const isOpen = siteNav.classList.toggle("open");
  menuToggle.setAttribute("aria-expanded", String(isOpen));
});

siteNav?.querySelectorAll("a").forEach((link) => {
  link.addEventListener("click", () => {
    siteNav.classList.remove("open");
    menuToggle?.setAttribute("aria-expanded", "false");
  });
});

renderPublications();
renderNews();
